consul:
  extends:
    file: docker-compose.yml
    service: consul
  ports:
    - 8500:8500
cloudapi:
  extends:
    file: docker-compose.yml
    service: cloudapi
  build: ./cloudapi-graphql
  links:
    - consul:consul
  environment:
    - PORT=3000
    - ROOT_URL=http://localhost:3000
    - CONSUL=consul
frontend:
  extends:
    file: docker-compose.yml
    service: frontend
  build: ./frontend
  links:
    - consul:consul
  environment:
    - PORT=8000
    - ROOT_URL=http://localhost:8000
    - CONSUL=consul
ui:
  extends:
    file: docker-compose.yml
    service: ui
  build: ./ui
  links:
    - consul:consul
  environment:
    - PORT=8080
    - ROOT_URL=http://localhost:8080
    - CONSUL=consul
nginx:
  extends:
    file: docker-compose.yml
    service: nginx
  build: ./nginx
  restart: never
  environment:
    - CONSUL=consul
  links:
    - consul:consul
  ports:
    - 8001:80
cockroach:
  extends:
    file: docker-compose.yml
    service: cockroach
  build: ./cockroach
  restart: never
  environment:
    - CONSUL=consul
  links:
    - consul:consul
